Add build script and hooks setuptest

diff --git a/scripts/git_hooks/pre-commit b/scripts/git_hooks/pre-commit
--- a/scripts/git_hooks/pre-commit
+++ b/scripts/git_hooks/pre-commit
@@ -1,3 +1,12 @@
-#!/bin/sh powershell
+#!/bin/sh
 
-python script/clang_format.py --apply --staged
+if command -v python3 >/dev/null 2>&1; then
+    PYTHON=python3
+elif command -v python >/dev/null 2>&1; then
+    PYTHON=python
+else
+    echo "Error: python not found in PATH"
+    exit 1
+fi
+
+$PYTHON scripts/code_format.py --check --staged
